
name: 'ten_fin'
version: '1.0.0'
config-version: 2

profile: 'ten_fin'

model-paths: ["models"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ten_fin:
    +dbt-osmosis: "_{model}.yml"   # Default for entire project
    staging:
      +materialized: table
    marts:
      +materialized: table