ten_fin:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: 'md:ten_fin'
      token: env_var('MOTHERDUCK_TOKEN')
    dev:
      type: duckdb
      path: './data/ten_fin_db_dev.duckdb'